language: python
env:
  global:
  - PYTHON_VERSION=$PYTHON_VERSION
matrix:
  include:
   - env: PYTHON_VERSION=3.6 
     os: linux
     arch: amd64
   - env: PYTHON_VERSION=3.6
     os: osx
     arch: amd64
     language: generic
   - env: PYTHON_VERSION=3.6
     os: linux
     arch: arm64
   - env: PYTHON_VERSION=3.6
     os: linux
     arch: arm64-graviton2
     virt: lxd
     group: edge
# command to install dependencies
install:
  - pip install codecov pytest pytest-cov
  - python setup.py develop
#environment settings
# command to run tests
script:
  - py.test  --cov-report term --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
