jobs:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64
   - os: linux
     arch: arm64-graviton2
     virt: lxd
     group: edge
language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install codecov pytest pytest-cov
  - python setup.py develop
#environment settings
# command to run tests
script:
  - py.test  --cov-report term --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
