@startgantt
printscale weekly
Project starts the 27th of march 2020
[Initialization] lasts 1 week
[MVP Package Development] lasts 17 weeks
[MVP Package Development] starts at [Initialization]'s end
[V-0.6.14 Developed] happens 2020-07-29
[V-0.7.17rc0 Update] lasts 5 weeks
[V-0.7.17rc0 Update] starts at [MVP Package Development]'s end
[V-0.7.17rc0 Deployed] happens 2020-08-29
[V-0.7.17rc1 Update] lasts 5 weeks
[V-0.7.17rc1 Update] starts at [V-0.7.17rc0 Update]'s end
[V-0.7.17rc1  Deployed] happens 2020-09-28
[V-0.7.17 Update] lasts 11 weeks
[V-0.7.17 Update] starts at [V-0.7.17rc1 Update]'s end
[V-0.7.17 Deployed] happens 2020-12-18
[V-0.8.20alpha Update] lasts 8 weeks
[V-0.8.20alpha Update] starts at 2020-11-30
[Documentation PDF, Website Design and Material] as [dw] lasts 37 weeks
[dw] starts at [Initialization]'s end
[Test Suite Implementation] lasts 7 weeks
[Test Suite Implementation] starts at [MVP Package Development]'s end
[Test Suite/CI Included] happens 2020-09-16
[Documentation Website Deployed] happens 2020-10-18
[Documentation PDF Finalized] happens 2020-12-21
[Initialization] is colored in Fuchsia/FireBrick
[MVP Package Development] is colored in GreenYellow/Green
[V-0.7.17rc0 Update] is colored in GreenYellow/Green
[V-0.7.17rc1 Update] is colored in GreenYellow/Green
[V-0.7.17 Update] is colored in GreenYellow/Green
[V-0.8.20alpha Update] is colored in GreenYellow/Green
[Test Suite Implementation] is colored in SkyBlue/Navy
[dw] is colored in Yellow/Orange
@endgantt